-- MySQL Script generated by MySQL Workbench
-- 09/29/16 15:28:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema genericsqlresultset
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema genericsqlresultset
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `genericsqlresultset` DEFAULT CHARACTER SET utf8 ;
USE `genericsqlresultset` ;

-- -----------------------------------------------------
-- Table `genericsqlresultset`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genericsqlresultset`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `newsletter` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genericsqlresultset`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genericsqlresultset`.`Team` (
  `idTeam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creationDate` DATE NOT NULL,
  `code` VARCHAR(80) NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genericsqlresultset`.`UserTeam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genericsqlresultset`.`UserTeam` (
  `idUser` INT NOT NULL,
  `idTeam` INT NOT NULL,
  `runnerNumber` INT NULL,
  `serial` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`, `idTeam`),
  INDEX `fk_User_has_Team_Team1_idx` (`idTeam` ASC),
  INDEX `fk_User_has_Team_User_idx` (`idUser` ASC),
  CONSTRAINT `fk_User_has_Team_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `genericsqlresultset`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_User_has_Team_Team1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `genericsqlresultset`.`Team` (`idTeam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genericsqlresultset`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genericsqlresultset`.`Payment` (
  `idPayment` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT(1) NOT NULL,
  `idTransaction` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(15,4) NOT NULL,
  `realized` DATE NOT NULL,
  `idTeam` INT NOT NULL,
  PRIMARY KEY (`idPayment`, `idTeam`),
  INDEX `fk_Payment_Team1_idx` (`idTeam` ASC),
  CONSTRAINT `fk_Payment_Team1`
    FOREIGN KEY (`idTeam`)
    REFERENCES `genericsqlresultset`.`Team` (`idTeam`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `genericsqlresultset`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `genericsqlresultset`;
INSERT INTO `genericsqlresultset`.`User` (`idUser`, `name`, `lastname`, `birthday`, `newsletter`) VALUES (1, 'John', 'Doe', '1980-01-01', 1);
INSERT INTO `genericsqlresultset`.`User` (`idUser`, `name`, `lastname`, `birthday`, `newsletter`) VALUES (2, 'Enrique', 'Hernández', '1994-01-28', 0);
INSERT INTO `genericsqlresultset`.`User` (`idUser`, `name`, `lastname`, `birthday`, `newsletter`) VALUES (3, 'Ñáñéñíñóñú', 'ÀÈÌÒÙ', '1960-12-12', 1);
INSERT INTO `genericsqlresultset`.`User` (`idUser`, `name`, `lastname`, `birthday`, `newsletter`) VALUES (4, 'âêîôû', 'Williamson', '1999-01-01', 0);

COMMIT;
